update_config=1
ctrl_interface=DIR=/run/wpa_supplicant GROUP=netdev

# Multiple "network" sections are allowed, wpa_supplicant will scan all available brodcasted SSIDs.
network={
        ssid=""
        psk=""
}

